Rails:
  Enabled: true

AllCops:
  Exclude:
  - db/schema.rb

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
  
Metrics/LineLength:
  Max: 100

EmptyMethod:
  EnforcedStyle: expanded
